# Generated by Django 5.0.4 on 2024-07-22 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=500)),
                ('reg_time', models.DateTimeField(verbose_name='registration date')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=500, verbose_name='registration number')),
                ('re_sell', models.BooleanField(verbose_name='used?')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_reg.car')),
            ],
        ),
        migrations.CreateModel(
            name='RegDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(verbose_name='car number registration date')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_reg.detail')),
            ],
        ),
    ]
