# Generated by Django 5.0.7 on 2024-07-26 09:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(default='Car Model', max_length=500)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2024, 7, 26, 19, 36, 57, 301365), verbose_name='registration date')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(default='A000AA', max_length=6)),
                ('reg_region', models.IntegerField(default=0)),
                ('re_sell', models.BooleanField(verbose_name='used?')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_reg.car')),
            ],
        ),
        migrations.CreateModel(
            name='RegDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.DateTimeField(default=datetime.datetime(2024, 7, 26, 19, 36, 57, 301365), verbose_name='car number registration date')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_reg.detail')),
            ],
        ),
    ]
