# Generated by Django 5.0.7 on 2024-07-27 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 11, 19, 23, 170635), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='regdetail',
            name='reg_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 11, 19, 23, 170635), verbose_name='car number registration date'),
        ),
    ]
