# Generated by Django 5.0.7 on 2024-07-27 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_reg', '0002_alter_car_reg_date_alter_regdetail_reg_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 11, 54, 16, 605402), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='regdetail',
            name='reg_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 11, 54, 16, 605402), verbose_name='car number registration date'),
        ),
    ]
