# Generated by Django 5.0.7 on 2024-07-27 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_reg', '0003_alter_car_reg_date_alter_regdetail_reg_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 12, 36, 3, 255482), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='regdetail',
            name='reg_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 12, 36, 3, 256483), verbose_name='car number registration date'),
        ),
    ]
