# Generated by Django 5.0.7 on 2024-07-27 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_reg', '0002_alter_car_reg_date_alter_regdetail_reg_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('bought_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='car_reg.car')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.buyers')),
            ],
        ),
    ]
