# Generated by Django 5.0.7 on 2024-07-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
