# Generated by Django 5.0.7 on 2024-07-27 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_reg', '0003_alter_car_reg_date_alter_regdetail_reg_time'),
        ('customers', '0002_delete_purchases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.buyers')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car', to='car_reg.car')),
                ('reg_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_reg.car')),
                ('purchases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.purchases')),
            ],
        ),
    ]
