# Generated by Django 5.0.7 on 2024-07-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_purchases_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
