# Generated by Django 5.0.7 on 2024-07-27 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='id',
        ),
        migrations.AddField(
            model_name='purchases',
            name='bought_cars',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customers.buyers'),
        ),
    ]
