# Generated by Django 5.0.7 on 2024-07-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_purchases_id_purchases_bought_cars_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
