# Generated by Django 5.0.7 on 2024-07-27 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_reg', '0004_alter_car_reg_date_alter_regdetail_reg_time'),
        ('customers', '0006_delete_purchases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customers.buyers')),
                ('bought_cars', models.ManyToManyField(to='car_reg.car')),
            ],
        ),
    ]
