# Generated by Django 5.0.7 on 2024-07-26 07:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 17, 46, 1, 159930), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='regdetail',
            name='reg_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 17, 46, 1, 159930), verbose_name='car number registration date'),
        ),
        migrations.CreateModel(
            name='NewRegDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.DateTimeField(default=datetime.datetime(2024, 7, 26, 17, 46, 1, 160931), verbose_name='car number registration date')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_reg.detail')),
            ],
        ),
    ]
