# Generated by Django 5.0.7 on 2024-07-26 07:46

from django.db import migrations


def copy_data(apps, schema_editor):
    Detail = apps.get_model('car_reg', 'Detail')
    RegDetail = apps.get_model('car_reg', 'RegDetail')
    NewRegDetail = apps.get_model('car_reg', 'NewRegDetail')
    for detail,reg_detail in zip(Detail.objects.all(), RegDetail.objects.all()):
        NewRegDetail.objects.get_or_create(detail=detail, reg_time=reg_detail.reg_time)


class Migration(migrations.Migration):

    dependencies = [
        ('car_reg', '0002_alter_car_reg_date_alter_regdetail_reg_time_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_data)
    ]
