# Generated by Django 5.0.7 on 2024-07-26 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_reg', '0003_auto_20240726_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegDetail',
        ),
        migrations.AlterField(
            model_name='car',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 17, 53, 40, 687607), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='newregdetail',
            name='reg_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 17, 53, 40, 688607), verbose_name='car number registration date'),
        ),
    ]
