# Generated by Django 5.0.7 on 2024-07-26 07:57

from django.db import migrations


def copy_data(apps, schema_editor):
    NewRegDetail = apps.get_model('car_reg', 'NewRegDetail')
    RegDetail = apps.get_model('car_reg', 'RegDetail')
    for new_reg_detail in NewRegDetail.objects.all():
        RegDetail.objects.get_or_create(detail=new_reg_detail.detail, reg_time=new_reg_detail.reg_time)


class Migration(migrations.Migration):

    dependencies = [
        ('car_reg', '0005_alter_car_reg_date_alter_newregdetail_reg_time_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_data)
    ]
