# Generated by Django 5.0.7 on 2024-07-26 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_reg', '0006_auto_20240726_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 18, 8, 50, 696060), verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='regdetail',
            name='reg_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 18, 8, 50, 696060), verbose_name='car number registration date'),
        ),
        migrations.DeleteModel(
            name='NewRegDetail',
        ),
    ]
