# Generated by Django 5.0.4 on 2024-05-10 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_model',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('[]', inverse_match=True)]),
        ),
    ]
