# Generated by Django 5.0.4 on 2024-05-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_tables', '0002_alter_carmodel_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_model',
            field=models.CharField(max_length=500),
        ),
    ]
